### ISSUE TITLE
First Milestone

### ISSUE THREAD

**Issue by KyleHu14** [KyleHu14/job-tracker-api#2]
- [x] Create dummy routes (without supabase integration) for the job_app router
  - [x] Create job_app route
  - [x] Get job_app route
  - [x] Delete job_app route
  - [x] Edit job_app route
- [x] Add users model
- [x] Add a user router (also without supabase integration)
  - [x] Create user route
  - [x] Fetch user info route
